/*
 * This source file was generated by the Gradle 'init' task
 */
package license

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'com.tutorial.license' plugin.
 */
class LicensePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply('com.tutorial.license')

        then:
        project.tasks.findByName("greeting") != null
    }
}
